/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AISearchModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/WallpaperCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/WallpaperGrid`; params?: Router.UnknownInputParams; } | { pathname: `/services/testUnsplash`; params?: Router.UnknownInputParams; } | { pathname: `/services/unsplash`; params?: Router.UnknownInputParams; } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/wallpaper/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AISearchModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BottomNavBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoadingSkeleton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/WallpaperCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/WallpaperGrid`; params?: Router.UnknownOutputParams; } | { pathname: `/services/testUnsplash`; params?: Router.UnknownOutputParams; } | { pathname: `/services/unsplash`; params?: Router.UnknownOutputParams; } | { pathname: `/category/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/wallpaper/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/AISearchModal${`?${string}` | `#${string}` | ''}` | `/components/BottomNavBar${`?${string}` | `#${string}` | ''}` | `/components/Button${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/LoadingSkeleton${`?${string}` | `#${string}` | ''}` | `/components/WallpaperCard${`?${string}` | `#${string}` | ''}` | `/components/WallpaperGrid${`?${string}` | `#${string}` | ''}` | `/services/testUnsplash${`?${string}` | `#${string}` | ''}` | `/services/unsplash${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AISearchModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSkeleton`; params?: Router.UnknownInputParams; } | { pathname: `/components/WallpaperCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/WallpaperGrid`; params?: Router.UnknownInputParams; } | { pathname: `/services/testUnsplash`; params?: Router.UnknownInputParams; } | { pathname: `/services/unsplash`; params?: Router.UnknownInputParams; } | `/category/${Router.SingleRoutePart<T>}` | `/wallpaper/${Router.SingleRoutePart<T>}` | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/wallpaper/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
